# Generated by Django 3.0.4 on 2020-04-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200406_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='importance',
            new_name='important',
        ),
        migrations.AlterField(
            model_name='todo',
            name='memo',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
